### ISSUE TITLE
Crash serer

### ISSUE THREAD

**Issue by ladysdani** [McMelonTV/PrisonEssentialsScorehudAddon#2]
I put addons in scorehud and when a player joins the server crashes, in console by error the addons can you help me?

**Comment by McMelonTV** [comment]
i will look at it

**Comment by McMelonTV** [comment]
can you send me the crashdump?

**Comment by ladysdani** [comment]
ok

**Comment by McMelonTV** [comment]
I was testing it and it works just fine for me. Even if a new player joins.... We were like 20 players on the server and it didn't crashed
